// This file mirrors the structure generated by the FlutterFire CLI so
// Dreamflow's Firebase configurator can inject your real values without
// hitting runtime errors on non-target platforms.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - rerun the FlutterFire CLI to add it.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - rerun the FlutterFire CLI to add it.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9lRk4rUReBCsM8EHFvELEew0Ouv0iOyc',
    appId: '1:73008181996:web:76d64606b564b9bad76bc9',
    messagingSenderId: '73008181996',
    projectId: 'break-away365-36gi4f',
    authDomain: 'break-away365-36gi4f.firebaseapp.com',
    storageBucket: 'break-away365-36gi4f.firebasestorage.app',
    measurementId: 'G-QRS20EC2BK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTYWIrGHGlsPL8pbVG-6iYbMaToTdhrvI',
    appId: '1:73008181996:android:099937e184971942d76bc9',
    messagingSenderId: '73008181996',
    projectId: 'break-away365-36gi4f',
    storageBucket: 'break-away365-36gi4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJUNcYdPCxq5hKjlBasb0oGudyVrgVTOQ',
    appId: '1:73008181996:ios:77049b8a2ebafad2d76bc9',
    messagingSenderId: '73008181996',
    projectId: 'break-away365-36gi4f',
    storageBucket: 'break-away365-36gi4f.firebasestorage.app',
    androidClientId: '73008181996-0b70133q9msulffo8orcbpnojr9l6l2b.apps.googleusercontent.com',
    iosClientId: '73008181996-0hr41tpdgnuq63mq0v0kr1qiov8eqn3v.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MACOS_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosClientId: 'YOUR_MACOS_CLIENT_ID',
    iosBundleId: 'YOUR_MACOS_BUNDLE_ID',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_WINDOWS_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );
}